name: 002-build-push

on:
  workflow_dispatch:

jobs:
  build-push:
    env:
        IMAGE: ${{ secrets.REGISTRY_LOGIN_SERVER }}/thebank
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

    - name: Generate build ID
      id: prep
      run: |
          branch=${GITHUB_REF##*/}
          sha=${GITHUB_SHA::8}
          ts=$(date +%s)
          echo "::set-output name=BUILD_ID::${branch}-${sha}-${ts}"

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and publish container image with tag
      uses: docker/build-push-action@v2
      with:
          push: true
          context: ./thebank
          file: ./thebank/Dockerfile
          tags: |
                        ${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }}